import Bar from './bar/index'
import Header from './header/index'
import Footer from './footer/index'
import Content from './content/index'
import Slide from './slide/index'
import ProductItem from './product-item/index'
import Division from './other/division'
import Pop from './pop/index'
import Back from './back/index'
import Submit from './submit/index'
export default {Bar, Header, Footer, Content, Slide, ProductItem, Division, Pop, Back, Submit}